// Edit this collection to replace the sample content. Optional image: './assets/photo.jpg'.
export const stories = [
 {title:'The long way home',quote:'Sometimes, the long way home is exactly where you need to be.',author:'Alex',place:'Around the corner',body:'I took a different turning on the way home. Just one street over, the familiar city felt completely new. I stayed a little longer than I planned.'},
 {title:'An ordinary kind of magic',quote:'Nothing special happened. And somehow, that was everything.',author:'Sam',place:'A quiet afternoon',body:'The kettle boiled. The afternoon light moved across the floor. For once, there was nowhere else I needed to be.'},
 {title:'A seat by the window',quote:'The world looks different from a seat by the window.',author:'Charlie',place:'The morning train',body:'Every morning I watch the same rooftops pass. Today I noticed a garden on one of them. I wonder how many other things I have been looking at without seeing.'},
 {title:'Hello, neighbour',quote:'We had lived next door for years before we learned each other’s names.',author:'Jamie',place:'Our building',body:'One small hello became a conversation. Then another. Now the place I live feels a little more like somewhere I belong.'},
 {title:'A small beginning',quote:'You do not always know when something is beginning.',author:'Robin',place:'The first day',body:'There was no grand announcement. Just a small decision to try something different, and the next day to try it again.'},
 {title:'The sound of the city',quote:'I missed the noise more than I thought I would.',author:'Drew',place:'The street below',body:'Footsteps, a closing shop, someone laughing across the road. The sounds I used to ignore became the sounds that told me I was home.'},
 {title:'A little more time',quote:'For the first time in a long time, I was not in a hurry.',author:'Morgan',place:'Sunday morning',body:'I left my phone in my pocket and walked without a destination. The morning seemed to open up around me.'},
 {title:'Things we keep',quote:'It is only a photograph. It is also a whole afternoon.',author:'Taylor',place:'An old album',body:'I cannot remember who took it. But I remember the wind, and what we were laughing about, and the feeling of having the whole day ahead of us.'},
 {title:'A place to return to',quote:'Some places remember you, even when everything else changes.',author:'Casey',place:'The old neighbourhood',body:'The shops were different. The corner was not. I stood there for a moment, finding my way back to an earlier version of myself.'},
 {title:'Learning to listen',quote:'The best part of the conversation was the part where I listened.',author:'Riley',place:'At the kitchen table',body:'We had nowhere to go and nothing to solve. So we talked. By the time the tea went cold, I understood a little more.'},
 {title:'Just around the corner',quote:'There is always something you have not discovered yet.',author:'Quinn',place:'A new route',body:'A narrow lane, a patch of sunlight, an open door. It did not take a big journey to find a new perspective.'},
 {title:'See you tomorrow',quote:'A small promise can make the world feel a little less large.',author:'Avery',place:'The end of the day',body:'Before we went our separate ways, we said we would meet again. It was a simple thing to look forward to. It was enough.'}
];
